### ISSUE TITLE
Have a Language class

### ISSUE THREAD

**Issue by andela-bmakinwa** [andela-gogbara/lifelist-api#25]
Going through your codebase, I can see that you have error messages and success messages which are good. However, when you want to change a particular message, you'd have to repeat efforts for all files with that message.

It would be good if you had a class or hash for your error and success messages. Just like the one rails provides in a model's instance.

**Comment by andela-bmakinwa** [comment]
This issue has not been fixed. Check your spec and app files well.

**Comment by andela-gogbara** [comment]
I did not consider my spec files in my previous implementation when I used a concern. I resolved the issue by creating a **Languages** Poro which is being used by both app and spec files.
