### ISSUE TITLE
Pagination not functioning well

### ISSUE THREAD

**Issue by andela-bmakinwa** [andela-gogbara/lifelist-api#26]

**Comment by andela-bmakinwa** [comment]
This issue has not been fixed. I attempted paginating and the first bucketlist created was not displayed with a query string `page=1&limit=1`.

**Comment by andela-gogbara** [comment]
Sorry for not spotting this earlier. The error was caused by the way PG ordered records. I have resolved the issue by adding an order I want PG to use.
